# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    my_user_provider:
        class: UserBundle\Security\Core\User\MyFOSUBUserProvider
        arguments: ['@fos_user.user_manager', { facebook: facebook_id }]

    admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Category }

    admin.blog_post:
        class: AppBundle\Admin\BlogPostAdmin
        arguments: [~, AppBundle\Entity\BlogPost, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Blog post }

    admin.user:
        class: UserBundle\Admin\UserAdmin
        arguments: [~, UserBundle\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: User }

    admin.group:
        class: UserBundle\Admin\GroupAdmin
        arguments: [~, UserBundle\Entity\Group, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Group }

    admin.businessCard:
        class: AppBundle\Admin\BusinessCardAdmin
        arguments: [~, AppBundle\Entity\BusinessCard, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Business Card }

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
