# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    user_provider:
        class: UserBundle\Security\Core\User\MyFOSUBUserProvider
        arguments: ['@fos_user.user_manager', { facebook: facebook_id }]

    admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Category }

    admin.blog_post:
        class: AppBundle\Admin\BlogPostAdmin
        arguments: [~, AppBundle\Entity\BlogPost, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Blog post }

    admin.businessCard:
        class: UserBundle\Admin\BusinessCardAdmin
        arguments: [~, UserBundle\Entity\BusinessCard, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Business Card, show_in_dashboard: false }

    admin.tag:
        class: UserBundle\Admin\TagAdmin
        arguments: [~, UserBundle\Entity\Tag, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Tag }

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
