services:
    user_provider:
        class: UserBundle\Security\Core\User\MyFOSUBUserProvider
        arguments: ['@fos_user.user_manager', { facebook: facebook_id }]

    admin.form.registration:
        class: UserBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: user_registration }

    admin.business_card:
        class: UserBundle\Admin\BusinessCardAdmin
        arguments: [~, UserBundle\Entity\BusinessCard, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Business Card }

    admin.tag:
        class: UserBundle\Admin\TagAdmin
        arguments: [~, UserBundle\Entity\Tag, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Tag }