parameters:
    sonata.user.admin.user.class: YS\UserBundle\Admin\UserAdmin

twig:
    form_themes:
        - 'YSUserBundle::form/fields.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        types:
            json: Sonata\Doctrine\Types\JsonType

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: YS\UserBundle\Entity\User
    registration:
        form:
            type: YS\UserBundle\Form\Type\RegistrationFormType
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
    group:
        group_class: YS\UserBundle\Entity\Group

sonata_user:
    class:
        user: YS\UserBundle\Entity\User
        group: YS\UserBundle\Entity\Group

sonata_admin:
    title:      Symfony
    dashboard:
        blocks:
            - { position: left, type: sonata.admin.block.admin_list }
        groups:
            blog:
                label: Blog
                items:
                    - admin.blog_post
                    - admin.category
            user:
                label: Users management
                items:
                    - sonata.user.admin.user
                    - sonata.user.admin.group
                    - admin.tag
                    - admin.business_card
    templates:
        layout:  YSUserBundle::SonataAdminBundle\base.html.twig

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:

hwi_oauth:
    connect:
        account_connector: my_user_provider
    firewall_names: [main]
    resource_owners:
        facebook:
            type:                facebook
            client_id:           "%facebook_client_id%"
            client_secret:       "%facebook_client_secret%"
            scope:               "email"
            infos_url:           "https://graph.facebook.com/me?fields=id,first_name,last_name,email"
        gplus:
            type:              google
            client_id:         "%google_client_id%"
            client_secret:     "%google_client_secret%"
            scope:             "email profile"